spring:
  datasource:
    url: jdbc:mysql://117.72.36.179:3306/openlynxe_db1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lifl1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  ai:
    memory:
      mysql:
        enabled: true
